INSERT INTO topics (name, category, description) VALUES
('SQL', 'Core', 'Relational querying, optimization, indexing and tuning'),
('Databricks', 'Platform', 'Lakehouse engineering and optimization in Databricks'),
('GitHub', 'Collaboration', 'Version control and workflow automation'),
('Azure Data Factory', 'Cloud ETL', 'Pipeline orchestration and ELT patterns'),
('Microsoft Fabric', 'Cloud Analytics', 'OneLake, lakehouse, and analytics engineering'),
('GenAI', 'AI', 'LLM fundamentals and data use cases'),
('Vector Databases', 'AI', 'Semantic retrieval and vector indexing'),
('LangChain', 'AI', 'RAG orchestration and prompt chaining'),
('Azure OpenAI', 'AI', 'Enterprise LLM workloads on Azure'),
('RAG', 'AI', 'Retrieval-augmented generation architecture'),
('Prompt Engineering', 'AI', 'Prompt structure, constraints, and evaluation'),
('DevOps', 'Engineering', 'Automation, reliability and release processes'),
('Terraform', 'Infra as Code', 'Cloud provisioning with IaC'),
('Bicep', 'Infra as Code', 'Azure native IaC templates'),
('Azure DevOps', 'Engineering', 'Boards, repos and pipelines'),
('CI/CD', 'Engineering', 'Build, test and deployment automation'),
('Delta Lake', 'Storage', 'ACID tables and medallion architecture'),
('Spark', 'Compute', 'Distributed processing and optimization'),
('PySpark', 'Compute', 'Python-based Spark transformations and tuning'),
('Lakehouse', 'Architecture', 'Unified data architecture principles'),
('OneLake', 'Architecture', 'Unified storage in Microsoft Fabric'),
('Unity Catalog', 'Governance', 'Data governance and access controls'),
('Data Modeling', 'Design', 'Dimensional and normalized modeling'),
('Data Warehousing', 'Design', 'Warehouse design and optimization'),
('Capstone Projects', 'Learning', 'Portfolio-grade implementation projects'),
('System Design', 'Architecture', 'Scalable data platform design'),
('Certifications', 'Career', 'Role-based certification preparation')
ON CONFLICT (name) DO NOTHING;

